openadr/api/urls.py
from django.conf.urls import url, include
from api import views
from django.conf import settings
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

app_name = 'api'

urlpatterns = [
    url(r'ven_test/$', views.OADRPoll.as_view(), name='test_ven'),

]

urlpatterns += router.urls

openadr/vtn/urls.py
# -*- coding: utf-8 -*- {{{
# vim: set fenc=utf-8 ft=python sw=4 ts=4 sts=4 et:

# Copyright (c) 2017, Battelle Memorial Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation
# are those of the authors and should not be interpreted as representing
# official policies, either expressed or implied, of the FreeBSD
# Project.
#
# This material was prepared as an account of work sponsored by an
# agency of the United States Government.  Neither the United States
# Government nor the United States Department of Energy, nor Battelle,
# nor any of their employees, nor any jurisdiction or organization that
# has cooperated in the development of these materials, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness or any
# information, apparatus, product, software, or process disclosed, or
# represents that its use would not infringe privately owned rights.
#
# Reference herein to any specific commercial product, process, or
# service by trade name, trademark, manufacturer, or otherwise does not
# necessarily constitute or imply its endorsement, recommendation, or
# favoring by the United States Government or any agency thereof, or
# Battelle Memorial Institute. The views and opinions of authors
# expressed herein do not necessarily state or reflect those of the
# United States Government or any agency thereof.
#
# PACIFIC NORTHWEST NATIONAL LABORATORY
# operated by BATTELLE for the UNITED STATES DEPARTMENT OF ENERGY
# under Contract DE-AC05-76RL01830
# }}}

from django.conf.urls import url
from django.views.generic import RedirectView
from vtn import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

app_name = 'vtn'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/vtn/login')),

    url(r'^home/$',views.overview, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^customer-detail/(?P<pk>\w+)$', views.CustomerDetailView.as_view(), name='customer_detail'),
    url(r'^site-detail/(?P<pk>\w+)$', views.SiteDetailView.as_view(), name='site_detail'),
    url(r'^dr_event/$', login_required(views.DREventAdd.as_view()), name='dr_event'),
    url(r'^customer-edit/(?P<pk>[0-9]+)$', views.CustomerUpdate.as_view(), name='customer_update'),
    url(r'customer/add/$', views.CustomerCreate.as_view(), name='customer_add'),
    url(r'^export/(?P<pk>[0-9]+)/$', login_required(views.dr_event_export), name='export_dr_events_csv'),
    url(r'^report/$', login_required(views.report), name='report'),
    url(r'^export/filter/$', login_required(views.get_more_tables), name='get_more_tables'),
    url(r'^dr-event/add/$', login_required(views.get_dr_event_form), name='get_dr_event_form'),
    url(r'site/create/(?P<pk>[0-9]+)/$', login_required(views.CreateSiteView.as_view()), name='create_site'),
    url(r'^home/(?P<pk>[0-9]+)/$', login_required(views.delete_dr_event), name='dr_event_delete'),
    url(r'dr_event/(?P<pk>[0-9]+)/$', login_required(views.dr_event_dispatch), name='dr_event_dispatch'),
    url(r'dr_event/view/(?P<pk>[0-9]+)/$', login_required(views.DREventCreate.as_view()), name='dr_event_update'),
    url(r'dr_event/detail/(?P<pk>[0-9]+)/$', login_required(views.DREventDetail.as_view()), name='dr_event_detail'),
    url(r'dr_event/detail/(?P<pk>[0-9]+)/customer/$', login_required(views.get_dr_event_details), name='dr_event_get_details'),
    url(r'^home/(?P<pk>[0-9]+)/$', login_required(views.cancel_dr_event), name='dr_event_cancel'),

    url(r'password_change/$', login_required(views.change_password), name='change_password'),
]

urlpatterns += router.urls

openadr/templates/admin_base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
{% load static %}
{% load activeurl %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'pics/kisensum.ico' %}"/>



</head>


<body>
    <div id="container">
    {% if user.is_authenticated %}
    <center>
    <h1 class="page-title">Utility OpenADR Application </h1>
    </center>
     <nav class="navbar navbar-expand-lg navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    {% activeurl %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vtn:home' %}">Overview</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vtn:report' %}">Report</a>
      </li>
        <li class="nav-item last">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
    </ul>
  <span class="nav-item dropdown">

            <a name='welcome_menu' href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome {{ user.username }} </a>
            <ul class="dropdown-menu">
                {% if user.has_usable_password %}
                    <li><a href="{% url 'vtn:change_password' %}">Change password </a></li>
                {% endif %}
            <li> <a name='logoff' href="{% url 'vtn:logout' %}">Logoff</a></li>
            </ul>
        </span>
  </div>
        {% endactiveurl %}
  </nav>
    {% endif %}


{% block admin %} {% endblock admin %}
</div>

</body>
<footer>
        <a href="http://www.kisensum.com"><center><small>Kisensum Utility OpenADR demo application</small></center></a>
    </footer>



</html>

openadr/templates/base.html
<!DOCTYPE html>
<html>
<html lang="en" xml:lang="en" xmlns= "http://www.w3.org/1999/xhtml">
<meta http-equiv="Content-Language" content="en_US">
<head>
<meta charset="utf-8">
{% load static %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/errors.css' %}" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/js/DateTimeShortcuts2.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/scrollbar.css' %}" />


{% load bootstrap4 %}
{% bootstrap_css %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/tables.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/base_css.css' %}">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'pics/kisensum.ico' %}"/>

</head>

{% load bootstrap_tags %}
{% load activeurl %}
{% load widget_tweaks %}


<body>
    <div id="container">
    {% if user.is_authenticated %}
    <center>
    <h1>Utility OpenADR Application </h1>
    </center>
     <nav class="navbar navbar-expand-lg navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    {% activeurl %}
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vtn:home' %}">Overview</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vtn:report' %}">Report</a>
      </li>
        <li class="nav-item last">
            {% if request.user.is_superuser %}
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            {% else  %}
            <a class="nav-link disabled-link" style="disabled: disabled" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
      </li>
    </ul>
  <span class="nav-item dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome {{ user.username }} </a>
            <ul class="dropdown-menu">
                {% if user.has_usable_password %}
                    <li><a href="{% url 'vtn:change_password' %}">Change password </a></li>
                {% endif %}
            <li> <a href="{% url 'vtn:logout' %}">Logoff</a></li>
            </ul>
        </span>
  </div>
        {% endactiveurl %}
  </nav>
    {% endif %}
              <div class="row justify-content-start titleDiv">
                    <div class="col-sm-6 heading">
                        <h1>{% block heading %} {% endblock %}</h1>
                    </div>
            </div>
        {% block content %}

        {% endblock content %}
</div>


</body>
<footer>
        <a href="http://www.kisensum.com"><center><small>Kisensum Utility OpenADR demo application</small></center></a>
    </footer>


<script type="text/javascript">

    $(document).ready(function() {
        $('a.disabled-link').click(function() {return false;});
        $('#backButton').on('click', function() {
            window.history.back();
        });
    });
</script>



</html>

openadr/templates/basewithpics.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
{% load static %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/errors.css' %}" />
    <script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/js/DateTimeShortcuts2.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/scrollbar.css' %}" />

{% load bootstrap4 %}
{% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.tablesorter.js' %}"></script>


</head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% load bootstrap_tags %}
{% load widget_tweaks %}

<style>

    #container {
        height: 100%;
        background-color: lightgray;
    }

    .row {
        max-height: 50%;
    }

    #backgroundImageOne {
        display: inline;
        float: left;
        margin: 4% 8%;
    }

    img.bg {
        width: 150px;
        height: 150px;
    }

    #backgroundImageTwo {
        float: right;
        margin: 4% 8%;
    }

    .title {
        postion: relative;
        top: 50%;
        transform:translateY(-50%);
        -webkit-transform: translateY(-50%);
    }

    #first-row {
        height: 7%;
    }
    html, body {
        height: 100%;
    }


    footer {
        background-color : lightgrey;
    }

    h1{
        font-weight: normal;
        font-size: 2.5rem;
    }

    h2 {
        font-weight: normal;
    }

    * {
        font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
    }

</style>
<body>
    <div id="container">
    <div class="row justify-content-center" id="first-row">
        {% if user.is_authenticated %}
            <div class="col-2">
                <a href="{% url 'vtn:home' %}"><button type="submit" class="btn btn-primary btn-lg">Home</button></a>
            </div>
            <div class="col-2">
                <a href="{% url 'vtn:logout' %}"><button type="submit" class="btn btn-danger btn-lg">Logoff</button></a>
            </div>

        {% else %}
            <a href="{% url 'vtn:login' %}"></a>
        {% endif %}

    </div>
    <div class="row justify-content-between align-items-center">
            <div class="col-3">
                <img id="backgroundImageOne" class="bg" src="{% static 'pics/utility.jpg' %}">
            </div>
                <h1> Utility OpenADR Application </h1>
            <div class="col-3">
                <img id="backgroundImageTwo" class="bg" src="{% static 'pics/pnnl.jpg' %}">
            </div>

        </div>
    {% block content %}
    {% endblock content %}
    </div>
</body>
<footer>
        <a href="http://www.kisensum.com"><center><small>Kisensum Utility OpenADR demo application</small></center></a>
    </footer>
</html>

openadr/templates/logged_out.html
{% extends 'basewithpics.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>
<script type="text/javascript" src="/static/js/DateTimeShortcuts2.js"></script>
<script type="text/javascript" src="/static/admin/js/calendar.js"></script>

{% load bootstrap4 %}
{% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href={% static 'css/base_css.css'%}>



    <style>
    h1, h2 {
        font-weight: normal;
    }
    </style>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
    {% if user.is_authenticated %}
        <meta http-equiv="refresh" content="0; {% url 'vtn:home' %}" />
    {% else %}
        <center>
        <h2>You have been logged out</h2>
               <a href="{% url 'vtn:login' %}"><button style="width:5cm" class="btn btn-primary" type="submit"><big><big>Login</big></big></button></a>
        </center>
    {% endif %}
{% endblock content %}

openadr/templates/login.html
{% extends 'basewithpics.html' %}
{% load static %}

    {% block content %}
        <link rel="stylesheet" type="text/css" href={% static 'css/base_css.css'%}>
    {% if user.is_authenticated %}
        <meta http-equiv="refresh" content="0; {% url 'vtn:home' %}" />
    {% else %}
        <center>
        <h2>Please Enter Your Credentials</h2>
            <br>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button name="login" style="width:5cm" class="btn btn-primary" type="submit"><big><big>Login</big></big></button>
            </form>
            <br>
{#        <a href="{% url 'vtn:signup' %}"><button style="width:5cm" class="btn btn-primary" type="submit"><big><big>Sign up</big></big></button></a>#}
        </center>
    {% endif %}
    {% endblock %}

openadr/templates/signup.html
{% extends 'basewithpics.html' %}

{% block content %}
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">
    <style>
    h2 {
    font-size: 16px;
    margin-top: 5%;
    padding: 0;
    margin-left: 5%;
}

    form {
        margin-left: 5%;
        margin-top: 2%;
    }

    html {
        background-color: lightgrey;
    }
        .h1, h1 {
        margin-bottom: .5rem;
        font-family: inherit;
        line-height: 1.1;
        color: black;
        margin-top: 0;
    }
    .h1, h1 {
        font-size: 2.5rem;
    }
    .row, .col {
        background-color: lightgrey;
    }

    .col-2 {
        text-align: center;
    }
    .title {
        margin-bottom: .5rem;
        font-family: inherit;
        font-weight: 500;
        line-height: 1.1;
        color: inherit;
        font-size: 2.5rem;
}

    .second_row {
        margin-top: 3%;
    }

    .end-label {
        padding-right: 5%;
        margin-right: 5%;
    }
    .notification-label {
        text-align: center;
        padding-left: 10%;
    }

    .last-row {
        margin-top : 3%;
    }

    .non-field-errors, .field-errors {
        color: red;
    }

    ul li {
        list-style-type: none;
    }

    .clockbox ul {
        max-height: 100px;
        overflow-y: scroll;
    }

    .h1, h1 {
        font-size: 2.5rem;
    }

    .h1, h1 {
        margin-bottom: .5rem;
        font-family: inherit;
        line-height: 1.1;
        color: black;
        margin-top: 0;
    }

    label {
        display: block;
    }

    h1 {
    margin-bottom: .5rem;
    font-family: inherit;
    font-weight: 500;
    line-height: 1.1;
    color: inherit;
}
    </style>


    {% if user.is_authenticated %}
    <h1> please logout before you sign up </h1>
    <a href="{% url 'vtn:logout' %}"> <button type="button">Go to logout page</button></a>
    {% else %}
          <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
    {% endif %}
{% endblock content %}