openadr/api/urls.py
from django.conf.urls import url, include
from api import views
from django.conf import settings
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

app_name = 'api'

urlpatterns = [
    url(r'ven_test/$', views.OADRPoll.as_view(), name='test_ven'),

]

urlpatterns += router.urls

openadr/vtn/urls.py
# -*- coding: utf-8 -*- {{{
# vim: set fenc=utf-8 ft=python sw=4 ts=4 sts=4 et:

# Copyright (c) 2017, Battelle Memorial Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation
# are those of the authors and should not be interpreted as representing
# official policies, either expressed or implied, of the FreeBSD
# Project.
#
# This material was prepared as an account of work sponsored by an
# agency of the United States Government.  Neither the United States
# Government nor the United States Department of Energy, nor Battelle,
# nor any of their employees, nor any jurisdiction or organization that
# has cooperated in the development of these materials, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness or any
# information, apparatus, product, software, or process disclosed, or
# represents that its use would not infringe privately owned rights.
#
# Reference herein to any specific commercial product, process, or
# service by trade name, trademark, manufacturer, or otherwise does not
# necessarily constitute or imply its endorsement, recommendation, or
# favoring by the United States Government or any agency thereof, or
# Battelle Memorial Institute. The views and opinions of authors
# expressed herein do not necessarily state or reflect those of the
# United States Government or any agency thereof.
#
# PACIFIC NORTHWEST NATIONAL LABORATORY
# operated by BATTELLE for the UNITED STATES DEPARTMENT OF ENERGY
# under Contract DE-AC05-76RL01830
# }}}

from django.conf.urls import url
from django.views.generic import RedirectView
from vtn import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter

router = DefaultRouter()

app_name = 'vtn'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/vtn/login')),

    url(r'^home/$',views.overview, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^customer-detail/(?P<pk>\w+)$', views.CustomerDetailView.as_view(), name='customer_detail'),
    url(r'^site-detail/(?P<pk>\w+)$', views.SiteDetailView.as_view(), name='site_detail'),
    url(r'^dr_event/$', login_required(views.DREventAdd.as_view()), name='dr_event'),
    url(r'^customer-edit/(?P<pk>[0-9]+)$', views.CustomerUpdate.as_view(), name='customer_update'),
    url(r'customer/add/$', views.CustomerCreate.as_view(), name='customer_add'),
    url(r'^export/(?P<pk>[0-9]+)/$', login_required(views.dr_event_export), name='export_dr_events_csv'),
    url(r'^report/$', login_required(views.report), name='report'),
    url(r'^export/filter/$', login_required(views.get_more_tables), name='get_more_tables'),
    url(r'^dr-event/add/$', login_required(views.get_dr_event_form), name='get_dr_event_form'),
    url(r'site/create/(?P<pk>[0-9]+)/$', login_required(views.CreateSiteView.as_view()), name='create_site'),
    url(r'^home/(?P<pk>[0-9]+)/$', login_required(views.delete_dr_event), name='dr_event_delete'),
    url(r'dr_event/(?P<pk>[0-9]+)/$', login_required(views.dr_event_dispatch), name='dr_event_dispatch'),
    url(r'dr_event/view/(?P<pk>[0-9]+)/$', login_required(views.DREventCreate.as_view()), name='dr_event_update'),
    url(r'dr_event/detail/(?P<pk>[0-9]+)/$', login_required(views.DREventDetail.as_view()), name='dr_event_detail'),
    url(r'dr_event/detail/(?P<pk>[0-9]+)/customer/$', login_required(views.get_dr_event_details), name='dr_event_get_details'),
    url(r'^home/(?P<pk>[0-9]+)/$', login_required(views.cancel_dr_event), name='dr_event_cancel'),

    url(r'password_change/$', login_required(views.change_password), name='change_password'),
]

urlpatterns += router.urls

openadr/vtn/models.py
# -*- coding: utf-8 -*- {{{
# vim: set fenc=utf-8 ft=python sw=4 ts=4 sts=4 et:

# Copyright (c) 2017, Battelle Memorial Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation
# are those of the authors and should not be interpreted as representing
# official policies, either expressed or implied, of the FreeBSD
# Project.
#
# This material was prepared as an account of work sponsored by an
# agency of the United States Government.  Neither the United States
# Government nor the United States Department of Energy, nor Battelle,
# nor any of their employees, nor any jurisdiction or organization that
# has cooperated in the development of these materials, makes any
# warranty, express or implied, or assumes any legal liability or
# responsibility for the accuracy, completeness, or usefulness or any
# information, apparatus, product, software, or process disclosed, or
# represents that its use would not infringe privately owned rights.
#
# Reference herein to any specific commercial product, process, or
# service by trade name, trademark, manufacturer, or otherwise does not
# necessarily constitute or imply its endorsement, recommendation, or
# favoring by the United States Government or any agency thereof, or
# Battelle Memorial Institute. The views and opinions of authors
# expressed herein do not necessarily state or reflect those of the
# United States Government or any agency thereof.
#
# PACIFIC NORTHWEST NATIONAL LABORATORY
# operated by BATTELLE for the UNITED STATES DEPARTMENT OF ENERGY
# under Contract DE-AC05-76RL01830
# }}}

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField


class Customer(models.Model):
    name = models.CharField('Name', db_index=True, max_length=100, unique=True)
    utility_id = models.CharField('Utility ID', max_length=100, unique=True)
    contact_name = models.CharField('Contact Name', max_length=100, blank=True)
    phone_number = models.CharField('Phone Number', max_length=13, null=True)

    def get_absolute_url(self):
        return reverse_lazy('vtn:customer_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "{}".format(self.name)

    def sites(self):
        return self.site_set.all()


class DRProgram(models.Model):

    class Meta:
        verbose_name_plural = "DR Programs"
        verbose_name = "DR Program"

    name = models.CharField('Program Name', max_length=100, unique=True)
    sites = models.ManyToManyField('Site', blank=True)

    def __str__(self):
        return self.name


class Site(models.Model):
    customer = models.ForeignKey(Customer)
    site_name = models.CharField('Site Name', max_length=100)
    site_id = models.CharField('Site ID', max_length=100)
    ven_id = models.CharField('VEN ID', max_length=100, unique=True, blank=True)
    ven_name = models.CharField('VEN Name', max_length=100, unique=True)
    site_location_code = models.CharField('Site Location Code', max_length=100)
    ip_address = models.CharField('IP address', max_length=100, blank=True)
    site_address1 = models.CharField('Address Line 1', max_length=100)
    site_address2 = models.CharField('Address Line 2', max_length=100, blank=True, null=True)
    city = models.CharField('City', max_length=100)
    state = models.CharField('State (abbr.)', max_length=2)
    zip = models.CharField('Zip', max_length=5)
    contact_name = models.CharField('Contact Name', max_length=100)
    phone_number = models.CharField('Phone Number', max_length=13)
    online = models.BooleanField(default=False)
    last_status_time = models.DateTimeField('Last Status Time', blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy('vtn:customer_detail', kwargs={'pk': self.customer.pk})

    def __str__(self):
        return "({}) {}".format(self.customer.name, self.site_name)


class DREvent(models.Model):

    class Meta:
        verbose_name_plural = "DR Events"
        verbose_name = "DR Event"

    STATUS_CHOICES = (
        ('scheduled', 'scheduled'),
        ('far', 'far'),
        ('near', 'near'),
        ('active', 'active'),
        ('completed', 'completed'),
        ('cancelled', 'cancelled'),
        ('unresponded', 'unresponded')
    )
    
    SIGNAL_NAME_CHOICES = (
        ('LOAD_DISPATCH','LOAD_DISPATCH'),
        ('ELECTRICITY_PRICE','ELECTRICITY_PRICE')
    )
    
    SIGNAL_TYPE_CHOICES = (
        ('setpoint','setpoint'),
        ('price','price')
    )

    dr_program = models.ForeignKey(DRProgram)
    scheduled_notification_time = models.DateTimeField('Scheduled Notification Time')
    start = models.DateTimeField('Event Start')
    end = models.DateTimeField('Event End')
    sites = models.ManyToManyField(Site, through='SiteEvent', related_name='Sites1')
    modification_number = models.IntegerField('Modification Number', default=0)
    status = models.CharField('Event Status', max_length=100, choices=STATUS_CHOICES, default='far')
    last_status_time = models.DateTimeField('Last Status Time', blank=True, null=True)
    superseded = models.BooleanField('Superseded', default=False)
    event_id = models.IntegerField('Event ID')
    intervals = JSONField()
    signal_name = models.CharField('Signal Name', max_length=100, choices=SIGNAL_NAME_CHOICES, default='LOAD_DISPATCH')
    signal_type = models.CharField('Signal Type', max_length=100, choices=SIGNAL_TYPE_CHOICES, default='setpoint')

    deleted = models.BooleanField(default=False)

    def __str__(self):
        return "{}: starts at {}. Ends at {}".format(self.dr_program.name, self.start, self.end)

    def get_absolute_url(self):
        return reverse_lazy('vtn:home')


class SiteEvent(models.Model):

    class Meta:
        verbose_name_plural = "Site Events"

    STATUS_CHOICES = (
        ('scheduled', 'scheduled'),
        ('far', 'far'),
        ('near', 'near'),
        ('active', 'active'),
        ('completed', 'completed'),
        ('cancelled', 'cancelled'),
        ('unresponded', 'unresponded')
    )

    OPT_IN_CHOICES = (
        ('optIn', 'optIn'),
        ('optOut', 'optOut'),
        ('none', 'Neither')
    )

    VEN_STATUS_CHOICES = (
        ('not_told', 'not_told'),
        ('told', 'told'),
        ('acknowledged', 'acknowledged')
    )

    dr_event = models.ForeignKey(DREvent)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default='scheduled')
    notification_sent_time = models.DateTimeField('Notification Sent Time', blank=True, null=True)
    last_status_time = models.DateTimeField('Last Status Time')
    modification_number = models.IntegerField('Modification Number', default=0)
    opt_in = models.CharField(max_length=100, choices=OPT_IN_CHOICES, default='none')
    ven_status = models.CharField(max_length=100, choices=VEN_STATUS_CHOICES, default='not_told')
    last_opt_in = models.DateTimeField('Last opt-in', blank=True, null=True)
    site = models.ForeignKey(Site)
    previous_version = models.ForeignKey('self', blank=True, null=True)
    deleted = models.BooleanField(default=False)


class Telemetry(models.Model):

    class Meta:
        verbose_name_plural = "Telemetry"

    site = models.ForeignKey(Site)
    created_on = models.DateTimeField(auto_created=True)
    reported_on = models.DateTimeField(null=True, blank=True)
    baseline_power_kw = models.FloatField('Baseline Power (kw)', blank=True, null=True)
    measured_power_kw = models.FloatField('Measured Power (kw)', blank=True, null=True)
    battery_voltage_v = models.FloatField('Battery Voltage (V)', blank=True, null=True)


class Report(models.Model):

    REPORT_STATUS_CHOICES = (
        ('active', 'active'),
        ('cancelled', 'cancelled'),
        ('cancelled_requested', 'cancelled_requested'),
    )

    report_status = models.CharField('Report Status', max_length=100, choices=REPORT_STATUS_CHOICES, default='active')
    report_request_id = models.CharField('Report Request ID', max_length=100, blank=True, null=True, unique=True)
    ven_id = models.CharField('VEN ID', max_length=100, blank=True)

openadr/templates/vtn/change_password.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">

    {% load bootstrap4 %}
    {% bootstrap_css %}
        <style>
        ul li {
        list-style-type: none;
    }

        .form-row {
            background-color: lightgrey;
        }

        input {
            overflow: hidden;
        }
    .btn-primary {
        background-color: #417690;
        border-color: #417690;
    }
    </style>

<!-- Container -->
<div id="container">
    <!-- Content -->
    <div id="content" class="colM">

        <h1>Password change</h1>
        <div id="content-main">

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-lg btn-primary" name="change_password" type="submit">Change Password</button>
  </form></div>



        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>

{% endblock %}

openadr/templates/vtn/clean_dr_event_filter.html
{% for event in data %}
    <tr>
         <td>{{ event.dr_program }}</td>
         <td>{{ event.scheduled_notification_time }}</td>
         <td>{{ event.start }}</td>
         <td>{{ event.end }}</td>
         <td>{{ event.numSites }}</td>
        <td> {{ event.status | capfirst }}</td>
         <td> <a href="{% url 'vtn:export_dr_events_csv' event.pk %}">Export </a> </td>
    </tr>
{% endfor %}

openadr/templates/vtn/dr_event_detail.html
{% extends 'base.html' %}
{% load static %}
{% load timetags %}

 {% block heading %}

     Event Detail: {{ event.dr_program }} <br>

    {% endblock heading %}


{% block content %}


<link href="/static/graph/nv.d3.css" rel="stylesheet" type="text/css">
<script src="/static/graph/d3.min.js" charset="utf-8"></script>
<script src="/static/graph/nv.d3.js"></script>
{% load bootstrap4 %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/event_detail.css' %}">
<script src="{% static 'js/jquery.floatThead.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.js"></script>
<script data-require="moment-timezone-with-data@0.4.0" data-semver="0.4.0"
        src="http://momentjs.com/downloads/moment-timezone-with-data.js"></script>
{% load admin_static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dr_event_detail.css' %}">

<div class="row justify-content-around">
    <div class="col-sm-4">
        <nav class="nav nav-tabs nav-stacked" id="myTab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
               aria-controls="nav-home" aria-expanded="true">Graph</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-sites_details" role="tab"
               aria-controls="nav-profile">Site Details</a>
        </nav>
    </div>
<div class="col-4" style="text-align: center">
        <div id="event_details">
                <div class="row justify-content-between">
                    <div class="col-sm-2" style="font-weight: bold">Notification <br></div>
                    <div class="col-sm-5">{{ event.scheduled_notification_time }}</div>
                </div>
                <div class="row justify-content-between">
                    <div class="col-sm-2" style="font-weight: bold">Start <br></div>
                    <div class="col-sm-5">{{ event.start }}</div>
                </div>
                <div class="row justify-content-between">
                    <div class="col-sm-2" style="font-weight: bold">End <br></div>
                    <div class="col-sm-5">{{ event.end }}</div>
                </div>
                <div class="row justify-content-between">
                    <div class="col-sm-2" style="font-weight: bold">Status <br></div>
                    <div class="col-sm-5">{{ event.status | capfirst }}</div>
                </div>

            </div>
    <br> <br>
                <button type="button" id="cancel_event" class="btn btn-lg btn-danger" data-toggle="modal"
                    data-target="#cancelModal">Cancel Event</button>
                    <br>
    <br>

    </div>
</div>

    {% if no_data != True %}
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
         <div class="row justify-content-center">
             <div class="col-md-2">
                <h3>Customer</h3>
                        {{ customerForm.customer }}
             </div>
             <div class="col-md-2">
                 <h3>Site</h3>
                        {{ siteForm.site }}
             </div>
        </div>

<br> <br>
<center>
<table id="chart" frame="border", width="1200px">
    <th>
        <div id="chart" class='with-3d-shadow with-transitions'>
            <svg style="height:450px;width:1200px;background-color: white"></svg>
        </div>
    </th>
</table>
    <br> <br>
</center>
<br> <br> <br> <br>
  </div>
        {% else %}
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
<center>

    <h2> No data for event </h2>
</center>
  </div>

    {% endif %}

<div class="tab-pane fade" id="nav-sites_details" role="tabpanel" aria-labelledby="nav-sites_details-tab">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="tableInDiv">
         <table id="siteTable" class="table table-bordered table-striped table-hover table-condensed">
                <thead>
                <tr>
                    <th class="col-sm-2">Site </th>
                    <th class="col-sm-2"> Notification Sent Time</th>
                    <th class="col-sm-2">Opt-in</th>
                    <th class="col-sm-2">Last opt-in</th>
                    <th class="col-sm-2">Most recent power (kw)</th>
                </tr>
                </thead>
                <tbody>
                {% for site_event in site_events %}
                    <tr>
                    <td style="text-align: left">{{ site_event.site }}</td>
                    <td>{{ site_event.notification_sent_time}}</td>
                        {% if site_event.opt_in == 'optIn' %}
                            <td style="background-color: green">Opted in</td>
                        {% elif site_event.opt_in == 'optOut' %}
                            <td style="background-color: #a31813">Opted out</td>
                        {% else %}
                            <td>{{ site_event.opt_in | capfirst }}  </td>
                        {% endif %}
                    <td>{{ site_event.last_opt_in}}</td>
                    {% if site_event.last_stat > 0 %}
                        <td class="negative"> -{{ site_event.last_stat }}</td>
                    {% elif site_event.last_stat < 0 %}
                        <td class="positive"> +{{ site_event.last_stat }}</td>
                        {% else %}
                        <td> {{ site_event.last_stat }}</td>
                    {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        </div>
    </div>
  </div>
</div>

<div id="cancelModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLiveLabel">Confirm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        </button>
      </div>
      <div class="modal-body" style="font-size: 14px">
          <center>
        <p>Are you sure you want to cancel this event? <br>
        It is already in progress.</p>
              </center>
      </div>
      <div class="modal-footer" style="text-align: center">
        <button type="button" style="margin: 0 auto" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a style="margin: 0 auto" href="{% url 'vtn:dr_event_cancel' pk %}" class="btn btn-danger">Cancel</a>

      </div>
    </div>
  </div>
</div>




    <!-- End second tab pane -->


<script type="text/javascript">
    $(document).on('change', '#id_customer', function() {
        console.log("change");

        if ($('#id_customer').val() == '') {
            $.ajax({
            type: "GET",
            url: "{% url 'vtn:dr_event_get_details' pk %}",
            data: {'customer': 'empty'}
        })
        .done(function(response) {
            $('#chart').html(response);
            $('#id_site').val('');
        });
        } else {

        $.ajax({
            type: "GET",
            url: "{% url 'vtn:dr_event_get_details' pk %}",
            data: {'customer': $('#id_customer').val()}
        })
        .done(function(response) {
            $('#chart').html(response);
            $('#id_site').val('');
        });
        }
    });

    $(document).on('change', '#id_site', function() {

        console.log($('#id_site').val());

        if ($('#id_site').val() == '') {
            $.ajax({
            type: "GET",
            url: "{% url 'vtn:dr_event_get_details' pk %}",
            data: {'site': 'empty'}
        })
        .done(function(response) {
            $('#chart').html(response);
            $('#id_customer').val('');
        });
        }
        else {

        $.ajax({
            type: "GET",
            url: "{% url 'vtn:dr_event_get_details' pk %}",
            data: {'site': $('#id_site').val()}
        })
        .done(function(response) {
            $('#chart').html(response);
            $('#id_customer').val('');
        });
        }
    });

</script>

<script>

    data_lineWithFocusChart = [
        {color:'red', key: 'Baseline Power (kw)',
        values: [
            {% for key, value in sum_baseline.items %}
            {x: {{key | toUnixSlice }}, y: {{ value }}},
            {% endfor %}

        ]},
        {color:'blue', key: 'Measured Power (kw)',
        values: [
            {% for key, value in sum_measured.items %}
            {x: ({{key | toUnixSlice }}), y: {{ value }}},
            {% endfor %}
        ]}
    ];



    nv.addGraph(function() {
        var chart = nv.models.lineWithFocusChart(
        );
        chart.margin({left: 100, bottom: 50, right: 100});
        chart.brushExtent([{{ start_focus | toUnix }} ,{{ end_focus | toUnix }} ]);


        chart.xAxis
            .axisLabel('Time')
            .tickFormat(function (d) {
                if (d != undefined) {
                    var offset = -1 * moment().zone();
                    return d3.time.format('%-I:%M %p')(moment(d).add(offset, 'm').toDate())

                }
            });

        chart.focusHeight(70 + 20);

        chart.focusMargin({ "bottom": 20 + 20 });

        chart.noData("There is no data to display");


        chart.x2Axis
            .tickFormat(function (d) {
                  var offset = -1 * moment().zone();
                  return d3.time.format('%-I:%M %p')(moment(d).add(offset, 'm').toDate())

            });

        chart.yAxis
            .axisLabel('Power(kW)')
            .tickFormat(d3.format(',.2f'));
        chart.y2Axis.tickFormat(d3.format(',.2f'));
        chart.useInteractiveGuideline(false);

        d3.select('#chart svg')
            .datum(data_lineWithFocusChart)
            .call(chart);

        nv.utils.windowResize(chart.update);

        return chart;
    });

</script>

    <script type="text/javascript">

    var $table = $('#siteTable');
    $table.floatThead({
        scrollContainer: function($table){
            return $table.closest('.tableInDiv');
        }
    });
</script>


{% endblock content %}

openadr/templates/vtn/dr_event_filter_form.html
{{ form.sites }}
<br> <br>
<span class="tip"> Hold down "Control", or "Command" on a Mac, to select more than one. </span>

openadr/templates/vtn/get_more_tables.html
{% for event in data %}
    <tr>
         <td>{{ event.dr_program }}</td>
         <td>{{ event.scheduled_notification_time }}</td>
         <td>{{ event.start }}</td>
         <td>{{ event.end }}</td>
         <td>{{ event.numSites }}</td>
         <td>{{event.status | capfirst }}</td>
        <td> <a href="{% url 'vtn:export_dr_events_csv' event.pk %}">Export </a> </td>
    </tr>
{% endfor %}